import numpy as np

a = np.arange(10,18).reshape(2,4)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,4)
d = list(range(4))
print(a)
print(b)
print(c)
print(d)

print(np.concatenate((a, b)))
print()
print(np.vstack((a, b)))
print()
print(np.vstack((a, d)))
print()
print(np.vstack((a, b, d)))
print()
print(np.hstack((a, c)))